version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  menu-service:
    image: menu-service
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
